version: '3.5'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: ergonomica
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    restart: unless-stopped
    entrypoint: |
      bash -c "
      docker-entrypoint.sh postgres &
      until pg_isready -h localhost -p 5432 -U postgres; do
        echo 'Waiting for Postgres to be ready...'
        sleep 2;
      done;
      if ! psql -h localhost -p 5432 -U postgres -d ergonomica -c \"SELECT * FROM pg_extension WHERE extname = 'pg_trgm';\" | grep -q 'pg_trgm'; then
        psql -h localhost -p 5432 -U postgres -d ergonomica -c 'CREATE EXTENSION IF NOT EXISTS pg_trgm;';
      fi
      wait
      "

  minio:
    image: minio/minio
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
    command: server /data --console-address :9001
    ports:
      - "9000:9000"
      - "9001:9001"

  tests:
    build:
      context: ./
      dockerfile: Dockerfile
    command:
      - sh 
      - -c
      - |
        npx prisma generate
        npx prisma db push
        npx ts-node prisma/seed.ts
        npm run build
        npm run e2e:headless
    ports:
      - "3000:3000"
    environment:
      SKIP_ENV_VALIDATION: "true"
      NODE_ENV: "test"
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/ergonomica"
      NEXTAUTH_SECRET: Xkr5urfEZ3FgcWNXna8Qci1Xc3oZC0jssHXAQXZP37k
      NEXTAUTH_URL: http://localhost:3000
      GOOGLE_CLIENT_ID: 1000000000000-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.apps.googleusercontent.com
      GOOGLE_CLIENT_SECRET: xxxxxxxxxxxxxxxxxxxxxxxxxxxx
      MINIO_ENDPOINT: http://minio:9000
      NEXT_PUBLIC_WEB_HOST: http://localhost:3000
      NEXT_PUBLIC_IMAGE_HOST: http://minio:9000/ergonomica-media
      NMI_SECURITY_KEY: 6457Thfj624V5r7WUwc5v6a68Zsd6YEm
      PROJECT_NAME: ergonomica
      NEXT_PUBLIC_LEAD_COOKIE: ergo_lead_id
      NEXT_PUBLIC_CART_COOKIE: ergo_cart_id
      S3_BUCKET_NAME: ergonomica-media
      AWS_REGION: us-east-1
      AWS_DEFAULT_REGION: us-east-1
    depends_on:
      - postgres
      - minio