import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'
import LeadGen from './components/leadGen'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
    const cookieStore = cookies()
    const visitorId = cookieStore.get('ergo_lead_id')?.value
    return (
    <html lang="en">
      <body className={inter.className}>
        <LeadGen visitorId={visitorId} />
        {children}
      </body>
    </html>
  )
}
