// AN ADMIN CAN SHARE A CART WITH A USER

// AN ADMIN CAN CREATE A CART WITHOUT A LEAD

// A LEAD NAVIGATES TO A CART URL THAT CONTAINS AN ID
    // THE CART DOESNT HAVE A LEAD
        // SUCCESS MESSAGE
        // SHOULD REFELCT THE NEW CART
        // THE LEADS ACTIVE CART SHOULD HAVE THE ID OF THE NEW CART
    // THE CART HAS A LEAD THAT MATCHES THE LEAD ID
        // NO MESSAGE
        // SHOULD BE REROUTED TO URL WITHOUT CART ID
        // SHOULD REFLECT USERS CURRENT CART
    // THE CART HAS A LEAD THAT MATCHES THE LEAD ID
        // ERROR MESSAGE
        // SHOULD BE REROUTED TO URL WITHOUT CART ID
        // SHOULD REFLECT USERS CURRENT CART